//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class informatica_industrial_dbEntities : DbContext
    {
        public informatica_industrial_dbEntities()
            : base("name=informatica_industrial_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<conversion> conversion { get; set; }
        public DbSet<direccion> direccion { get; set; }
        public DbSet<externo> externo { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<padre_componente> padre_componente { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<tipo_externo> tipo_externo { get; set; }
        public DbSet<tipo_producto> tipo_producto { get; set; }
        public DbSet<traduccion> traduccion { get; set; }
        public DbSet<unidad_medida> unidad_medida { get; set; }
        public DbSet<users> users { get; set; }
    }
}
