//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversion
    {
        public int U_medida_default { get; set; }
        public int U_medida { get; set; }
        public float Coeficiente { get; set; }
    
        public virtual unidad_medida unidad_medida { get; set; }
        public virtual unidad_medida unidad_medida1 { get; set; }
    }
}
