//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public direccion()
        {
            this.externo = new HashSet<externo>();
            this.externo1 = new HashSet<externo>();
            this.externo2 = new HashSet<externo>();
        }
    
        public int idDireccion { get; set; }
        public string Calle { get; set; }
        public int Numero { get; set; }
        public string Barrio { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public int CodigoPostal { get; set; }
        public string Direccioncol { get; set; }
    
        public virtual ICollection<externo> externo { get; set; }
        public virtual ICollection<externo> externo1 { get; set; }
        public virtual ICollection<externo> externo2 { get; set; }
    }
}
