//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class herramienta
    {
        public int idHerramienta { get; set; }
        public int idProducto { get; set; }
        public int idEstacion { get; set; }
        public float Uso { get; set; }
        public int UM_uso { get; set; }
    
        public virtual estacion estacion { get; set; }
    }
}
