//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.users = new HashSet<users>();
            this.traduccion = new HashSet<traduccion>();
        }
    
        public int idLanguage { get; set; }
        public string Language_Desc { get; set; }
    
        public virtual ICollection<users> users { get; set; }
        public virtual ICollection<traduccion> traduccion { get; set; }
    }
}
