//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento_maquina
    {
        public int idMantenimiento { get; set; }
        public int idMaquina { get; set; }
        public System.DateTime fecha_mantenimiento { get; set; }
        public string piezas_cambiadas { get; set; }
    }
}
