//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        public string ubicacion_origen { get; set; }
        public string ubicacion_destino { get; set; }
        public int idProducto { get; set; }
        public System.DateTime fecha_movimiento { get; set; }
        public float cantidad { get; set; }
        public int unidad_medida { get; set; }
        public int idRazon { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual unidad_medida unidad_medida1 { get; set; }
    }
}
