//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class operario_estacion
    {
        public int IdUser { get; set; }
        public int idEstacion { get; set; }
        public System.DateTime tiempo_comienzo { get; set; }
        public System.DateTime tiempo_finalizacion { get; set; }
    
        public virtual estacion estacion { get; set; }
        public virtual users users { get; set; }
    }
}
