//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.padre_componente = new HashSet<padre_componente>();
            this.padre_componente1 = new HashSet<padre_componente>();
        }
    
        public int idProducto { get; set; }
        public int idDescriptionP { get; set; }
        public int idTipo { get; set; }
        public int Unidad_id_Purchase { get; set; }
        public int Unidad_id_Aplication { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> User_Upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<padre_componente> padre_componente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<padre_componente> padre_componente1 { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        public virtual unidad_medida unidad_medida1 { get; set; }
    }
}
