//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.padre_componente = new HashSet<padre_componente>();
            this.padre_componente1 = new HashSet<padre_componente>();
        }
    
        public int idProducto { get; set; }
        public int idDescriptionP { get; set; }
        public int idTipo { get; set; }
        public int Unidad_id_Purchase { get; set; }
        public int Unidad_id_Aplication { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.DateTime> Last_Upd { get; set; }
        public Nullable<int> User_Upd { get; set; }
    
        public virtual ICollection<padre_componente> padre_componente { get; set; }
        public virtual ICollection<padre_componente> padre_componente1 { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
        public virtual unidad_medida unidad_medida { get; set; }
        public virtual unidad_medida unidad_medida1 { get; set; }
    }
}
