//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.users = new HashSet<users>();
        }
    
        public int idRole { get; set; }
        public int idDescriptionR { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
