//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_externo
    {
        public tipo_externo()
        {
            this.externo = new HashSet<externo>();
        }
    
        public int idTipo_Externo { get; set; }
        public int idDescriptionTE { get; set; }
    
        public virtual ICollection<externo> externo { get; set; }
    }
}
