//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muebleria
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_medida
    {
        public unidad_medida()
        {
            this.conversion = new HashSet<conversion>();
            this.conversion1 = new HashSet<conversion>();
            this.producto = new HashSet<producto>();
            this.producto1 = new HashSet<producto>();
        }
    
        public int idUnidad_Medida { get; set; }
        public int idDescriptionUM { get; set; }
        public int Factor_N { get; set; }
    
        public virtual ICollection<conversion> conversion { get; set; }
        public virtual ICollection<conversion> conversion1 { get; set; }
        public virtual ICollection<producto> producto { get; set; }
        public virtual ICollection<producto> producto1 { get; set; }
    }
}
